//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders_Engine_module_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class DiscountProductMap
    {
        public int MapID { get; set; }
        public int ProductID { get; set; }
        public int DiscountID { get; set; }
        public System.DateTime CreatedDate { get { return DateTime.Now; } set { } }
        public string CreatedBy { get { return "Admin"; } set { } }

        //For dropdown list
        public IEnumerable<SelectListItem> discountname { get; set; }
        public IEnumerable<SelectListItem> Productname { get; set; }

        public virtual Discount Discount { get; set; }
    }
}
